/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNav: typeof import('./src/components/appNav.vue')['default']
    AssistantDrawer: typeof import('./src/components/AssistantDrawer.vue')['default']
    DataFreshnessNotice: typeof import('./src/components/DataFreshnessNotice.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    GuestAccessBanner: typeof import('./src/components/GuestAccessBanner.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    NewUserGuide: typeof import('./src/components/NewUserGuide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
